Update README.md
san4ezy/django_softdelete pull request #4
Opened 2021-09-13 13:17 UTC by rnetonet

1. Corrects pip install command. The package name was missing a hyphen (https://pypi.org/project/django-soft-delete/).
2. Adds section directing to include in settings

2021-09-28 22:10 UTC, koffisani commented
This should merged.

2021-10-11 18:37 UTC, rnetonet commented
@san4ezy Could you give a look ? Thanks =)

2021-10-12 06:22 UTC, san4ezy commented
Hi, everyone! Sorry for delay!

Of course, I missed up the names 🙃 . Thank you! 

Regarding `INSTALLED_APPS`, it's not necessary. This package does not have its own db tables, it just gives its abstract models for inheritance your own models. `SoftDeleteModel` provides some fields and object managers, but does not store any data.

2021-10-13 05:34 UTC, san4ezy requested changes
@rnetonet could you please remove a part about settings, so I can merge this? It is not necessary to add package to the `INSTALLED_APPS`.

2021-10-14 22:47 UTC, rnetonet commented
@san4ezy lThe settings part was removed. Thanks for your feedback. If you need anything else, let me know =)

2021-10-15 07:02 UTC, merged

2021-10-15 07:04 UTC, san4ezy commented
Thank you guys! I merged it.